name: Compile lzfoo to WebAssembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-wasip1

    - name: Build lzfoo to WebAssembly
      working-directory: lzfoo
      run: cargo build --target wasm32-wasip1

    - name: debug list files
      run: ls -lR lzfoo target

    - name: Upload WebAssembly artifact
      uses: actions/upload-artifact@v4
      with:
        name: lzfoo.wasm
        path: lzfoo/target/wasm32-wasip1/debug/lzfoo.wasm