name: Compile lzfoo to WebAssembly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-wasip1

    - name: Build lzfoo to WebAssembly
      working-directory: lzfoo
      run: cargo build --target wasm32-wasip1
